name: benchmarks

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    # benchmark-macos:
    #     runs-on: ${{ matrix.os }}
    #     strategy:
    #         matrix:
    #             os: [macos-12]
    #     steps:
    #         -   uses: actions/checkout@v2
    #         -   name: run-benchmarks 
    #             run: |
    #                 cd Benchmarks
    #                 mkdir .data && tar -xf data.tar.xz -C .data
    #                 swift --version
    #                 swift run -c release benchmark .data/ftx.json
    #                 swift run -c release benchmark-aws-ipam .data/aws-ipamd.jsonl
    benchmark-linux:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-20.04]
                swift: [DEVELOPMENT-SNAPSHOT-2022-07-25-a]
        steps:
            -   uses: actions/checkout@v2
            
            -   name: cache swift toolchains
                uses: actions/cache@v2
                with:
                    path: swift-${{ matrix.swift }}.tar.gz
                    key: ${{ matrix.os }}:swift:${{ matrix.swift }}
                    
            -   name: cache status
                id:   cache_status
                uses: andstor/file-existence-action@v1
                with:
                    files: swift-${{ matrix.swift }}.tar.gz
            
            -   name: download swift toolchain 
                if: steps.cache_status.outputs.files_exists == 'false'
                run: curl https://download.swift.org/development/swift-${{ matrix.swift }}/swift-${{ matrix.swift }}-$(echo ${{ matrix.os }} | sed 's/[^a-zA-Z0-9]//g').tar.gz --output swift-${{ matrix.swift }}.tar.gz
            
            -   name: set up swift
                run: |
                    mkdir -p $GITHUB_WORKSPACE/swift-${{ matrix.swift }}
                    tar -xzf swift-${{ matrix.swift }}.tar.gz -C $GITHUB_WORKSPACE/swift-${{ matrix.swift }} --strip 1
                    echo "$GITHUB_WORKSPACE/swift-${{ matrix.swift }}/usr/bin" >> $GITHUB_PATH

            -   name: run-benchmarks 
                run: |
                    cd Benchmarks
                    mkdir .data && tar -xf data.tar.xz -C .data
                    swift --version
                    swift run -c release benchmark .data/ftx.json
                    swift run -c release benchmark-aws-ipam .data/aws-ipamd.jsonl
